### ISSUE TITLE
Properly scale the art

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/art-on-walls-prototype#2]
Given that we'll have the actual real-world proportions of the art, I *believe* we shouldn't need to make any assumptions here, we can just make it the actual real size.

**Comment by lazerwalker** [comment]
@orta I know specs you've written up talk about needing to make assumptions about scale based on e.g. phone height. You definitely need to do that in VR / screen-based 3D, but I don't _think_ we need to worry about that in AR (or at least in ARKit).

Modulo a tiny bit of camera/position 4D transform math to make sure we're dealing in the real-world coordinate system, saying 'this thing should be 24" x 36" at this `(x,y,z)`', we should be able to rely on ARKit and SceneKit to do the heavy lifting of making it properly scaled to the room for everyone.

(As an example, Ikea's app doesn't even give you the option to resize their furniture)

Let me know if I'm missing something obvious here.

**Comment by orta** [comment]
> (As an example, Ikea's app doesn't even give you the option to resize their furniture)

Ah, I did not know this, I should try it. If we can make it right outright, that's super awesome.

**Comment by lazerwalker** [comment]
Cool. I'm like 90% sure this is possible / actually pretty easy, so it sounds like the answer here is I'll bang on it until/when it turns out there's hidden complexity.

**Comment by lazerwalker** [comment]
Yeah, the coordinate system for ARKit is just in meters, so this is trivially easy to do right.

It's not exactly spot-on, but the variance seems to be caused by drift in ARKit's world detection, so it's not like we'll be able to reasonably improve on it.

@orta: assuming the model layer has picture size data, what unit does it use? It's easy for me to take in inches (or other) and convert to meters, but would be good to make the interface the right one.

**Comment by orta** [comment]
Let me check, we definitely have both cm and inches though

**Comment by orta** [comment]
Yep, both `dimensionsCM` and `dimensionsInches` [exist in the model](https://github.com/artsy/eigen/blob/master/Artsy/Models/API_Models/Partner_Metadata/Artwork.m#L63-L64)
