### ISSUE TITLE
Can tap and drag to reposition art

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/art-on-walls-prototype#4]
Moving your finger should slide the art along the x/y axis of the wall. Ignore the z axis for now.

**Comment by lazerwalker** [comment]
Rather than treating this like panning / a joystick, I'm treating the fake detected "wall" as a canvas. As you move your finger across the screen, we directly move the art along that axis to that point. This feels pretty natural for now.

To do:

- [x] Only trigger a move when you start by dragging on the art itself, instead of just tapping anywhere (Wallr and PictureThat both make you drag the art, Christie's just lets you tap to instantly move. Christie's interaction feels junky compared to them)
- [x] Performance is pretty bad. There may be low-hanging fruit, and then the next sensible step is to probably throttle movement calls
- [ ] This should be refactored to be a bit nicer than literally just doing it within `touchesMoved`
- [ ] Right now, we literally have a very large (but fixed-size) invisible plane sitting in the world. It'd be nice if we had a clever math way to generate that plane at the time we `hitTest`, but performance implications may mean we're better off keeping a single plane around rather than doing expensive math every touch event.

A question to ask others: in Apple's 3D placement examples, once you start moving the object, you have to modally confirm its new position, and can also snap back to its old position. Presumably we could also show a nice placeholder image while we move it instead of the real thing. I don't _think_ we want this, but worth calling out as an option.

**Comment by lazerwalker** [comment]
Just to write my thought process out for those reading along at home:

I ended up reverting the change that forces you to tap and drag on the art rather than just tap anywhere in the world to move it there. It felt better, but it seemed pretty easy to get into circumstances where ARKit glitching meant you couldn't actually grab the art. 

Open to discussion, but I assume erring on the side of "this won't fail in ways that causes the app to be unusable" is a better design choice than a slightly more natural interaction.

**Comment by lazerwalker** [comment]
Cool, this needs a refactor or two, but works, so gonna close this for now.

**Comment by orta** [comment]
👍
