### ISSUE TITLE
"Reset positioning" button

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/art-on-walls-prototype#7]
The spec suggests we need both a back button and a reset button, and that the back button will probably be provided as part of the Eigen wrapping nav code.

@orta I'm assuming that might mean that a 'reset' button should be part of a navcontroller? Worst case scenario, the minimal version of this is me implementing this is either exposing a public 'reset' function or throwing a button somewhere in the scenekit view, but I suspect you'll have more context to know what's best/easiest.

**Comment by orta** [comment]
Looks like this is probably going to be a modal VC, so Eigen'll provide an exit button.

WRT the reset button, I'd wire something simple up and see how it feels once design specs come though
