### ISSUE TITLE
Should we extrude art to create a sense of depth?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/art-on-walls-prototype#8]
Orta says Christie's does this.

The first naive thing to try: make the quad that the art is rendered on slightly thicker.

The slightly smarter thing: do we have data on artworks themselves that can inform how thick we render the canvas?

The most work: Is there a way we can be smart about actually rendering a 3D model of a frame of some sort? The natural conclusion of this is probably a complex frame selection UI that is almost certainly more work than we should do.

**Comment by orta** [comment]
> The natural conclusion of this is probably a complex frame selection UI that is almost certainly more work than we should do

Yep, it'll eventually be on my plate.

> : do we have data on artworks themselves that can inform how thick we render the canvas?

Yes -ish

We allow data input for this (screenshot from v2 API):

<img width="429" alt="screen shot 2017-11-14 at 9 58 14 pm" src="https://user-images.githubusercontent.com/49038/32816499-fa7a4c0a-c986-11e7-895d-8d99b74f5455.png">

But historically we've [not allowed View in Room for artworks with depth](https://github.com/artsy/eigen/blob/master/Artsy/Models/API_Models/Partner_Metadata/Artwork.m#L256-L274) as it can be an indication of a sculpture-ish work.

IMO, 

> make the quad that the art is rendered on slightly thicker

Then give it small black depth. It's not the ultimate answer, but it's good enough for today.

**Comment by lazerwalker** [comment]
Currently set as a 3/4" black canvas, with depth (currently in inches) as an optional parameter you can pass in when creating a config object.

I suspect we may want it to be smaller than that, but I'm embarrassingly not in a place right now where I can test on an actual wall.

![img_0171](https://user-images.githubusercontent.com/821238/32857883-45ceea5e-c9fe-11e7-9813-e7b75bcecf3d.PNG)
