### ISSUE TITLE
Should we tell people to put their phone right up on the wall, or 2 inches away?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/art-on-walls-prototype#9]
Orta's spec:

> Once ARKit says it knows enough about the room we present a screen asking someone to place their phone next to the wall ( need to test whether it makes sense to say “2 inches” or just use the phone position )

I suspect there are two separate — but interconnected — questions here:

1. From an implementation standpoint, do we just assume that the phone is directly against the wall, or do we assume the wall is 1-2 inches farther "forward" (from the frame of reference of the camera) from the phone position when the user taps?
2. From a design standpoint, do we explicitly tell people "put your phone two inches from the wall" or "put your phone up against the wall"?

**Comment by orta** [comment]
Yep, this is still a bit of an open question IMO, I think one way to derive an answer is to see how often ARKit disconnects and says you can't place an object down if you get _right up_ to the wall.

**Comment by lazerwalker** [comment]
Yeah, totally. 

In some of my testing, it seems like ARKit pretty immediately reconnects when you move away from the wall. If we want to tell people to put their phone right up against the wall, there might be a class of hacks surrounding "try to detect if AR has dropped because the phone is up against the wall vs for other reasons, and if the former then do some fudging to make it appear as if everything's okay until the user pulls their phone away"

**Comment by lazerwalker** [comment]
For now, it seems like ignoring ARKit's disconnected status still gives us great accuracy. You can put your phone right up to the wall, place the art, and the average drift between the fake vertical plane and the actual wall seems way lower than when you freehand it. 

There'll need to be a little bit of state tracking w.r.t when we're showing the error messages vs when we don't (TBD when we have actual designs) but this seems like the best solution for now.
